spring.batch.job.enabled: false

spring.servlet.multipart:
  max-file-size: ${MULTI_PART_MAX_FILE_SIZE:100MB}
  max-request-size: ${MULTI_PART_MAX_REQ_SIZE:100MB}

statement-processing.validation.storage-directory: ${PROC_VAL_STORAGE_DIR:/tmp}

auth.jwt:
  issuer: ${JWT_AUTH_ISSUER:Customer Statement Processor}
  secret: ${JWT_AUTH_SECRET:ej7+D6Hh2r2KBEIuoGz1RGjtXooObzebSSxNm7yu2YSkEKv8aQmC2iYuxXLkKYKgT1210e5ZKMoY4XM0uQnkJkKGA01tBWZK+Pi3zX+nZvVNTJbZwRSOyZ2bm99exCq+z6ER5q5XWes1G9/sG5rp7kK9bL/NdNdU13HAFjJew6NwyxIxFH5VhXWwtgIJy+1KcJ9+3kq6uYNylrPC2U1h0xvR9qQzi1D2m9H8ZA==}
  audience: ${JWT_AUTH_AUDIENCE:Jordaan}
  ttl-seconds: ${JWT_AUTH_TTL_SECS:600}
  test-user: ${JWT_TEST_USER} #REMOVE !!!
  test-password: ${JWT_TEST_PASSWORD} #REMOVE !!!

auditing.enable-web-interactions-logging: ${ENABLE_WEB_INTERACTIONS_LOGGING:true}